name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: make install
    
    - name: Lint code
      run: make lint
    
   # - name: Run tests
    #  run: make test
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/photo-app-repo:frontend-latest

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/photo-app-repo:backend-latest

    - name: Log out from Docker Hub
      run: docker logout


    

      
